config/routes.rb
Rails.application.routes.draw do
  get '/' =>  'site#home'

  get '/contact' => 'contact#contact'

  # get '/projects' => 'projects#index'

  # get '/projects/:id' => 'projects#show'

  # get '/projects/:project_id/entries' => 'entries#index'

  # get '/projects/:project_id/entries/new' => 'entries#new'

  resources :projects, only: [:index, :show] do
    resources :entries, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to(:project)
  validates :hours, presence: true
  validates :hours, numericality: true
  validates :minutes, presence: true
  validates :minutes, numericality: true
  validates :project_id, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many(:entries)
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: {maximum: 30}
  validates :name, format: {with: /[A-Za-z0-9\s]/}

  def self.iron_find(value)
    where(value).first
  end

  def self.clean_old
    where('created_at < ?', 1.week.ago).destroy_all
  end

  def self.last_created_projects(max)
    order('created_at DESC').limit(max)
  end

  def self.first_updated_projects(max)
    order('updated_at ASC').limit(max)
  end

  def total_hours_in_month(month, year)
    date = Time.new(year, month)
    project_entries = self.entries.where(date: date.beginning_of_month..date.end_of_month)
    total_minutes = project_entries.reduce(0) do |sum, entry|
      sum + entry.minutes + entry.hours*60
    end
    total_hours = total_minutes/60.0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def render_404(params)
    Rails.logger.warn("Tried to access #{params} which did not exist.")
    render "layouts/404"
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
    render 'contact'
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @project = Project.find_by(id: params[:project_id]) || render_404(params)
    date = Date.current
    @entries = Entry.where(
      project_id: params[:project_id]).where(
        date: date.beginning_of_month..date.end_of_month)
  end

  def new
    @project = Project.find(params[:project_id])
    @entry = @project.entries.new
  end

  def create
    @project = Project.find(params[:project_id])
    @entry = @project.entries.new(entry_params)

    if @entry.save
      flash[:notice] = 'Entry saved succesfully'
      redirect_to action: 'index', controller: 'entries', project_id: @project.id
    else
      flash.now[:alert] = @entry.errors.full_messages
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @entry = @project.entries.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update_attributes(entry_params)
      flash[:notice] = 'Entry updated succesfully'
      redirect_to action: 'index'
    else
      flash.now[:errors] = @entry.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @entry = @project.entries.find(params[:id])

    if @entry.destroy
      redirect_to action: 'index'
    end
  end

  private
  def entry_params
    params.require(:entry).permit(:hours, :minutes, :date)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.last_created_projects(20)
    if @projects.empty?
      render('no_project', layout: 'ironhack')
    end
  end

  def show
    @project = Project.find_by(id: params[:id]) || render_404(params)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    render 'home' # name of view template
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    if flash[:alert]
      flash_content_tag('alert')
    elsif flash[:notice]
      flash_content_tag('notice')

    end
  end

  def total_work_hours project
    date = Date.current
    total_hours = project.total_hours_in_month(date.month, date.year)
  end

  private
  def flash_content_tag type
    content_tag :div, class: 'message alert' do
        content_tag :p do
          flash[type.to_sym]
        end
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/contact/contact.html.erb
<h1>Contact</h1>

<p>You can reach us via e-mail in: contact@example.com</p>

app/views/entries/_form.html.erb
<% if flash[:alert] %>
YOU WOT MATE
<% end %>

<% if @entry.errors.any? %>
  <ul>
    <%= @entry.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@project, @entry] do |f| %>
  <%= f.label :hours %>
  <%= f.text_field :hours %>
  <br>
  <%= f.label :minutes %>
  <%= f.text_field :minutes %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>

  <%= f.submit 'Save' %>
<% end %>

<%= link_to "Cancel", project_entries_path %>

app/views/entries/edit.html.erb
<h2>Editing Entry <%= @entry.id %></h2>

<%= render 'form' %>

app/views/entries/index.html.erb
<%= flash_message %>

<h2><%= @project.name %></h2>

<ul>
  <% @entries.each do |entry| %>
    <li>
      <%= link_to "#{entry.hours} h #{entry.minutes} m - #{entry.date}",
      edit_project_entry_path(@project, entry.id) %>
      <%= link_to('Delete', project_entry_path(@project, entry),
        method: :delete, data: {confirm: 'Are you sure?'}) %>
    </li>
  <% end %>
</ul>

<p> Total hours worked this month <%= total_work_hours(@project) %></p>

<%= link_to 'Back to Projects', projects_path %>
<%= link_to 'New Entry', new_project_entry_path(@project.id) %>

app/views/entries/new.html.erb
<h2>Creating a new Entry for <%= @project.name %></h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/ironhack.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <header>
      <h1>Time Tracking Tool</h1>
    </header>

    <%= yield %>
    <footer>
      Ironhack - Rails Introduction
    </footer>
  </div>
</body>
</html>

app/views/projects/index.html.erb
<div class="container">
  <table class="table table-striped" style="margin-top: 20px; max-width: 500px;">
    <tr>
      <th>Project</th>
      <th>Date</th>
    </tr>
    <% @projects.each do |project| %>
      <tr>
        <td>
          <%= link_to(project.name, project_entries_path(project.id)) %>
          <% if project.description? %>
            - <%= project.description %>
          <% end %>
        </td>
        <% if project.created_at.today? %>
          <td><%= project.created_at %></td>
        <% else %>
          <td><%= project.updated_at %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/projects/no_project.html.erb
NO PROJEEEEEEECTS

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>

<p><%= @project.description %></p>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>
<p>Ironhack powered</p>